//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CommunityAssistEntities1 : DbContext
{
    public CommunityAssistEntities1()
        : base("name=CommunityAssistEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<BusinessRule> BusinessRules { get; set; }
    public virtual DbSet<CommunityService> CommunityServices { get; set; }
    public virtual DbSet<ContactType> ContactTypes { get; set; }
    public virtual DbSet<Donation> Donations { get; set; }
    public virtual DbSet<Employee> Employees { get; set; }
    public virtual DbSet<EmployeeJobTitle> EmployeeJobTitles { get; set; }
    public virtual DbSet<GrantReview> GrantReviews { get; set; }
    public virtual DbSet<Jobtitle> Jobtitles { get; set; }
    public virtual DbSet<Person> People { get; set; }
    public virtual DbSet<PersonAddress> PersonAddresses { get; set; }
    public virtual DbSet<PersonContact> PersonContacts { get; set; }
    public virtual DbSet<ServiceGrant> ServiceGrants { get; set; }
}
